#!/bin/bash

path="/sys/class/leds/asus::kbd_backlight"
if [ ! -e "$path" ]; then
  path="/sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight"
fi
# brightness vars
min=0
max=3
# step: represent the difference between previous and next brightness
step=1
previous=$(sudo cat ${path}/brightness)

function commit {
  if [[ $1 = [0-9]* ]]
  then
    if [[ $1 -gt $max ]]
    then
      next=$max
    elif [[ $1 -lt 0 ]]
    then
      next=0
    else
      next=$1
    fi
    echo $next | sudo tee ${path}/brightness > /dev/null
    exit 0
  else
    exit 1
  fi
}

case "$1" in
  next)
    if [[ $previous == $max ]]; then
      commit $min
    else
      commit $(($previous + $step))
    fi
    ;;
  up)
    commit $(($previous + $step))
    ;;
  down)
    commit $(($previous - $step))
    ;;
  max)
    commit $max
    ;;
  min)
    commit $min
    ;;
  on)
    $0 max
    ;;
  off)
    commit 0
    ;;
  show)
    echo $previous
    ;;
  night)
    commit 1
    ;;
  allowusers)
    # Allow members of users group to change brightness
    sudo chgrp arghya ${path}/brightness
    sudo chmod g+w ${path}/brightness
    ;;
  disallowusers)
    # Allow members of users group to change brightness
    sudo chgrp root ${path}/brightness
    sudo chmod g-w ${path}/brightness
    ;;
  *)
    commit $1
esac

exit 0
